/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.ShigureCoreRos1
{
    public class DetectedObjectList : Message
    {
        public const string RosMessageName = "shigure_core_ros1_msgs/DetectedObjectList";

        public Header header { get; set; }
        public DetectedObject[] object_list { get; set; }

        public DetectedObjectList()
        {
            this.header = new Header();
            this.object_list = new DetectedObject[0];
        }

        public DetectedObjectList(Header header, DetectedObject[] object_list)
        {
            this.header = header;
            this.object_list = object_list;
        }
    }
}
