/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ShigureCoreRos1
{
    public class PoseKeyPoints : Message
    {
        public const string RosMessageName = "shigure_core_ros1_msgs/PoseKeyPoints";

        public string people_id { get; set; }
        public BoundingBox bounding_box { get; set; }
        public PointData[] point_data { get; set; }

        public PoseKeyPoints()
        {
            this.people_id = "";
            this.bounding_box = new BoundingBox();
            this.point_data = new PointData[0];
        }

        public PoseKeyPoints(string people_id, BoundingBox bounding_box, PointData[] point_data)
        {
            this.people_id = people_id;
            this.bounding_box = bounding_box;
            this.point_data = point_data;
        }
    }
}
