/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.ShigureCoreRos1
{
    public class TrackedObjectList : Message
    {
        public const string RosMessageName = "shigure_core_ros1_msgs/TrackedObjectList";

        public Header header { get; set; }
        public TrackedObject[] tracked_object_list { get; set; }

        public TrackedObjectList()
        {
            this.header = new Header();
            this.tracked_object_list = new TrackedObject[0];
        }

        public TrackedObjectList(Header header, TrackedObject[] tracked_object_list)
        {
            this.header = header;
            this.tracked_object_list = tracked_object_list;
        }
    }
}
