/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ShigureCoreRos1
{
    public class TrackedObject : Message
    {
        public const string RosMessageName = "shigure_core_ros1_msgs/TrackedObject";

        public string object_id { get; set; }
        public string action { get; set; }
        //  take_out, stay, bring_in
        public BoundingBox bounding_box { get; set; }
        public Cube collider { get; set; }

        public TrackedObject()
        {
            this.object_id = "";
            this.action = "";
            this.bounding_box = new BoundingBox();
            this.collider = new Cube();
        }

        public TrackedObject(string object_id, string action, BoundingBox bounding_box, Cube collider)
        {
            this.object_id = object_id;
            this.action = action;
            this.bounding_box = bounding_box;
            this.collider = collider;
        }
    }
}
