//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrdfTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrdfTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- =================================================================================== --&gt;
        ///&lt;!-- |    This document was autogenerated by xacro from /home/catkin_ws/src/universal_robot/ur_description/urdf/ur5_joint_limited_robot.urdf.xacro | --&gt;
        ///&lt;!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | --&gt;
        ///&lt;!-- =================================================================================== --&gt;
        ///&lt;robot name=&quot;ur5&quot;&gt;
        ///  &lt;gazebo&gt;
        ///     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string UR5Tooltip {
            get {
                return ResourceManager.GetString("UR5Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;!-- =================================================================================== --&gt;
        ///&lt;!-- |    This document was autogenerated by xacro from /opt/ros/kinetic/share/turtlebot_description/robots/kobuki_hexagons_asus_xtion_pro.urdf.xacro | --&gt;
        ///&lt;!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | --&gt;
        ///&lt;!-- =================================================================================== --&gt;
        ///&lt;!--
        ///    - Base      : kobuki
        ///    - Stacks    : [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string xmlResFullRobot {
            get {
                return ResourceManager.GetString("xmlResFullRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;robot name=&quot;turtlebot&quot; xmlns:xacro=&quot;http://ros.org/wiki/xacro&quot;&gt;
        ///
        ///  &lt;link name=&quot;base_footprint&quot;/&gt;
        ///  &lt;joint name=&quot;base_joint&quot; type=&quot;fixed&quot;&gt;
        ///    &lt;origin rpy=&quot;0 0 0&quot; xyz=&quot;0 0 0.0102&quot;/&gt;
        ///    &lt;parent link=&quot;base_footprint&quot;/&gt;
        ///    &lt;child link=&quot;base_link&quot;/&gt;
        ///  &lt;/joint&gt;
        ///  &lt;tooltip name=&quot;base_tooltip&quot; topic=&quot;/test/topic&quot;&gt;
        ///	&lt;parent link=&quot;base_footprint&quot;/&gt;
        ///    &lt;origin rpy=&quot;0 0 0&quot; xyz=&quot;0 0 0.0102&quot;/&gt;
        ///  &lt;/tooltip&gt;
        ///&lt;/robot&gt; ähnelt.
        /// </summary>
        internal static string xmlResSingleNode {
            get {
                return ResourceManager.GetString("xmlResSingleNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;robot name=&quot;turtlebot&quot; xmlns:xacro=&quot;http://ros.org/wiki/xacro&quot;&gt;
        ///
        ///  &lt;link name=&quot;base_footprint&quot;/&gt;
        ///  &lt;joint name=&quot;base_joint&quot; type=&quot;fixed&quot;&gt;
        ///    &lt;origin rpy=&quot;0 0 0&quot; xyz=&quot;0 0 0.0102&quot;/&gt;
        ///    &lt;parent link=&quot;base_footprint&quot;/&gt;
        ///    &lt;child link=&quot;base_link&quot;/&gt;
        ///  &lt;/joint&gt;
        ///  &lt;tooltip name=&quot;base_tooltip&quot; topic=&quot;/test/topic&quot;&gt;
        ///	&lt;parent link=&quot;base_footprint&quot;/&gt;
        ///    &lt;origin rpy=&quot;0 0 0&quot; xyz=&quot;0 0 0.0102&quot;/&gt;
        ///  &lt;/tooltip&gt;
        ///  &lt;link name=&quot;base_link&quot;&gt;
        ///    &lt;visual&gt;
        ///      &lt;geometry&gt;
        ///        &lt;!-- ne [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string xmlResSingleNodeWithTooltip {
            get {
                return ResourceManager.GetString("xmlResSingleNodeWithTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- =================================================================================== --&gt;
        ///&lt;!-- |    This document was autogenerated by xacro from /home/catkin_ws/src/universal_robot/ur_description/urdf/ur3_joint_limited_robot.urdf.xacro | --&gt;
        ///&lt;!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | --&gt;
        ///&lt;!-- =================================================================================== --&gt;
        ///&lt;robot name=&quot;ur3&quot;&gt;
        ///  &lt;gazebo&gt;
        ///     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string xmlUr5 {
            get {
                return ResourceManager.GetString("xmlUr5", resourceCulture);
            }
        }
    }
}
