/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.PeopleDetectionRos1
{
    public class People : Message
    {
        public const string RosMessageName = "people_detection_ros1_msgs/People";

        public Header header { get; set; }
        public BoundingBox[] person_bouding_box_list { get; set; }
        public CompressedImage mask { get; set; }

        public People()
        {
            this.header = new Header();
            this.person_bouding_box_list = new BoundingBox[0];
            this.mask = new CompressedImage();
        }

        public People(Header header, BoundingBox[] person_bouding_box_list, CompressedImage mask)
        {
            this.header = header;
            this.person_bouding_box_list = person_bouding_box_list;
            this.mask = mask;
        }
    }
}
