/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ShigureCoreRos1
{
    public class Contacted : Message
    {
        public const string RosMessageName = "shigure_core_ros1_msgs/Contacted";

        public string event_id { get; set; }
        public string people_id { get; set; }
        public string object_id { get; set; }
        public string action { get; set; }
        public BoundingBox people_bounding_box { get; set; }
        public BoundingBox object_bounding_box { get; set; }
        public Cube object_cube { get; set; }

        public Contacted()
        {
            this.event_id = "";
            this.people_id = "";
            this.object_id = "";
            this.action = "";
            this.people_bounding_box = new BoundingBox();
            this.object_bounding_box = new BoundingBox();
            this.object_cube = new Cube();
        }

        public Contacted(string event_id, string people_id, string object_id, string action, BoundingBox people_bounding_box, BoundingBox object_bounding_box, Cube object_cube)
        {
            this.event_id = event_id;
            this.people_id = people_id;
            this.object_id = object_id;
            this.action = action;
            this.people_bounding_box = people_bounding_box;
            this.object_bounding_box = object_bounding_box;
            this.object_cube = object_cube;
        }
    }
}
