/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.ShigureCoreRos1
{
    public class DetectedObject : Message
    {
        public const string RosMessageName = "shigure_core_ros1_msgs/DetectedObject";

        public string action { get; set; }
        //  現状は take_out, bring_in
        public BoundingBox bounding_box { get; set; }
        public CompressedImage mask { get; set; }

        public DetectedObject()
        {
            this.action = "";
            this.bounding_box = new BoundingBox();
            this.mask = new CompressedImage();
        }

        public DetectedObject(string action, BoundingBox bounding_box, CompressedImage mask)
        {
            this.action = action;
            this.bounding_box = bounding_box;
            this.mask = mask;
        }
    }
}
