/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ShigureCoreRos1
{
    public class PointData : Message
    {
        public const string RosMessageName = "shigure_core_ros1_msgs/PointData";

        public string body_part_name { get; set; }
        public Point pixel_point { get; set; }
        public Point projection_point { get; set; }
        public float score { get; set; }

        public PointData()
        {
            this.body_part_name = "";
            this.pixel_point = new Point();
            this.projection_point = new Point();
            this.score = 0.0f;
        }

        public PointData(string body_part_name, Point pixel_point, Point projection_point, float score)
        {
            this.body_part_name = body_part_name;
            this.pixel_point = pixel_point;
            this.projection_point = projection_point;
            this.score = score;
        }
    }
}
