/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.OpenposeRos1
{
    public class PoseKeyPoints : Message
    {
        public const string RosMessageName = "openpose_ros1_msgs/PoseKeyPoints";

        public PoseKeyPoint[] pose_key_points { get; set; }

        public PoseKeyPoints()
        {
            this.pose_key_points = new PoseKeyPoint[0];
        }

        public PoseKeyPoints(PoseKeyPoint[] pose_key_points)
        {
            this.pose_key_points = pose_key_points;
        }
    }
}
