/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.OpenposeRos1
{
    public class PoseKeyPoint : Message
    {
        public const string RosMessageName = "openpose_ros1_msgs/PoseKeyPoint";

        public float x { get; set; }
        public float y { get; set; }
        public float score { get; set; }

        public PoseKeyPoint()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.score = 0.0f;
        }

        public PoseKeyPoint(float x, float y, float score)
        {
            this.x = x;
            this.y = y;
            this.score = score;
        }
    }
}
