/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.OpenposeRos1
{
    public class PoseKeyPointsList : Message
    {
        public const string RosMessageName = "openpose_ros1_msgs/PoseKeyPointsList";

        public Header header { get; set; }
        public PoseKeyPoints[] pose_key_points_list { get; set; }

        public PoseKeyPointsList()
        {
            this.header = new Header();
            this.pose_key_points_list = new PoseKeyPoints[0];
        }

        public PoseKeyPointsList(Header header, PoseKeyPoints[] pose_key_points_list)
        {
            this.header = header;
            this.pose_key_points_list = pose_key_points_list;
        }
    }
}
